### ISSUE TITLE
Nav Bar 

### ISSUE THREAD

**Issue by AutogolazzoJr** [lighthouse64/TSA_Website#17]
When the window is resized, the nav bar li's start stacking. Please fix.

**Comment by DarinMao** [comment]
We'll start working on (RWD)[https://en.wikipedia.org/wiki/Responsive_web_design] after we're done with research.

**Comment by DarinMao** [comment]
Although, it may be good to think about it now. What do you want to happen when the window gets too small? Do you want everything to stay on one line? I think that would not be very pretty, especially for mobile users.
My idea is that when the window gets too small, or if it is just too small to begin with, we stack all of the buttons and hide them inside of a "dropdown menu" kind of layout. When the user clicks/taps the button, all of the buttons come back out.

**Comment by DarinMao** [comment]
Kind of like [this](https://codepen.io/g13nn/pen/eHGEF)

**Comment by DarinMao** [comment]
If we agree to use Bootstrap, this problem will be almost fixed. It looks great on desktops and mobile phones, but there's a little space between the two that looks a little weird. I'll work to get it fixed.

**Comment by DarinMao** [comment]
Navbar fixed on all screen sizes! WOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO!
