### ISSUE TITLE
Ditch the php

### ISSUE THREAD

**Issue by AutogolazzoJr** [lighthouse64/TSA_Website#18]
Can we ditch the php and change the files to html? Php is hard af to debug.

**Comment by lighthouse64** [comment]
Affirmative

**Comment by lighthouse64** [comment]
True

**Comment by DarinMao** [comment]
Why are you debugging the PHP? It's working fine, just ignore it.

**Comment by DarinMao** [comment]
It's not just annoying for me, it should be annoying to you to have to edit every single file individually. However, if we can finalize the design of the navbar (We'll discuss on Thursday), we won't need to edit it anymore. 

If you haven't seen it already, the [404 page](http://mission-to-mars.000webhostapp.com/this-is-not-an-actual-page) tells you the URL of the page you tried to request. This is also done with PHP, so if you look at the source code you won't see any scripting there.

Both of these things can be done via jQuery, but it would be messy, and users could see the scripts that make it work. They could see the files that include the banner and footer. It also might be very slow on certain machines. If EVERYONE is okay with all of these caveats, then I can work to remove the PHP code and replace it with (jQuery load()'s)[http://api.jquery.com/load/].

**Comment by DarinMao** [comment]
Okay, since you think that "Php is hard af to debug" and that "PHP is cancer", then can you please propose your own solution before saying it sucks?

**Comment by AutogolazzoJr** [comment]
You are about to witness the strength of html and client-server-side
scripting languages.
php is cancer cancer cancer cancer
php is cancer cancer cancer cancer
php is cancer cancer cancer cancer
php is cancer! cancer! cancer!
php is an asshole
php is a retard
php is an asshole, who confuses little kids
php, server side code, github, c9.io, they are all CANCER!
I, ethan james, declare war on all server side scripting languages! Stop
the confusion of little kids!




Ok, now that I've had a laugh about that, the php should be fine. I am able
to preview it with adobe dreamweaver, and although it is not super
accurate, it works. Issue solved.
