### ISSUE TITLE
Proposal to move to c9.io

### ISSUE THREAD

**Issue by lighthouse64** [lighthouse64/TSA_Website#19]
Now I know this is a long stretch, but I honestly feel like it'll make things easier.  c9.io will work well with   the php because you can temporarily run a server on it, allowing you to see the style, and it will be automatically updated when you change it.  Also, it is collaborative, just like github, and it allows instant group chatting.  However, it doesn't have an issues page.

Here is the link.  I have cloned the github repo to this.
https://c9.io/lighthouse64/tsa-website

I think you have to make an account and request access before you can actually collaborate (sorry), but overall, I feel this will be a better web editor.  However, you can use your github account to login at c9.io, so that doesn't make any extra work 👍 :)

Please post your thoughts.

**Comment by DarinMao** [comment]
We need a credit card to sign up, and I can't really do that right now.

**Comment by lighthouse64** [comment]
Wait what the heck happened to this site.  I'm sorry, I didn't know that the site completely changed from when I last signed up.  When I signed up, I didn't need a credit card.

Again, sorry :/
