### ISSUE TITLE
MOVE TO BOOTSTRAP

### ISSUE THREAD

**Issue by DarinMao** [lighthouse64/TSA_Website#23]
I'll start to integrate Bootstrap into our pages (Branch: Bootstrap). Once everyone agrees, I'll merge it.

You're probably thinking, "HOLD ON DARIN! What the f*** is Bootstrap?" A quick Google would probably answer that question, but I'll spare you the searching. From http://getbootstrap.com/, "Bootstrap is the most popular HTML, CSS, and JS framework for developing responsive, mobile first projects on the web."

Basically, you can include the Bootstrap framework, and then you can just assign different classes to elements, and Bootstrap will format them automatically. See the [examples](http://getbootstrap.com/getting-started/#examples), and I'm sure you'll want to use Bootstrap.

By using Bootstrap, we can stop making fruitless attempts at formatting with manual CSS. Bootstrap will do that for us. And best of all, it is all responsive, making our site look _fabulous_ on desktop, tablets, phones, and pretty much any screen.

Our 112-line CSS file, is totally unnecessary. Using Bootstrap, we can cut that down quite a bit. Our site may look a bit different, but I assure you, it will all be for the best.

**Comment by DarinMao** [comment]
It's also really easy. I started this morning with absolutely no experience or knowledge about Bootstrap, and now, in 11 hours, I've changed the entire site to use Bootstrap.

**Comment by AutogolazzoJr** [comment]
idc go ahead.
