### ISSUE TITLE
Contributor

### ISSUE THREAD

**Issue by mineo333** [lighthouse64/TSA_Website#30]
Wait... Why am I still a contributor

Note to Darin: Keep track of your contributors; it could hurt you one day.....

**Comment by DarinMao** [comment]
I'm not the one who owns the repository. Blame Ryan for that...

...time to go send him another "WHY DID YOU DO THAT???!!!!!" email. That's the second one for today; a new record.

**Comment by DarinMao** [comment]
- [ ]
