### ISSUE TITLE
Dropdown Menus

### ISSUE THREAD

**Issue by mineo333** [lighthouse64/TSA_Website#32]
Look who needed Dropdown menus....

**Comment by mineo333** [comment]
Just for your info I still have my dropdown on my fork

**Comment by DarinMao** [comment]
As we added more pages it became apparent that a button for every page was just too much. I wanted a button for each section page, and then those section pages would link to the individual pages, but in the end we still decided on dropdown menus. 

We won't be needing your dropdown menus for two specific reasons:

1. You're not in our team, and certain team members (*ahem* Ethan *ahem*) don't seem to like you
2. There are several problems in your code

What problems? Here you go:

1. It's not responsive
2. The buttons fold if the buttons are too big and/or if the screen is too narrow (such as on a mobile phone)
3. The dropdown menu doesn't close onmouseout (only onmouseover)
4. Many browsers don't support `matches` (Line 8 of MyScript.js)

There are also some cringy things you (as a programmer) should avoid:

1. Naming files and other things with "my" eg. "MyScript.js", "myFunction()"
2. Using `<table>` for non-tabular data
3. Capitalized filenames

Also, you don't even need JS for dropdown menus. You can do it with pure CSS (Look into `:hover`).

Last thing, in your last comment, you said:

> Just for your info I still have my dropdown on my fork

Your fork, eh? Well, fork you! :laughing:

**Comment by DarinMao** [comment]
And also stop using this as a comment section.This place is for **ISSUES!!!!!!** So please don't post anything that's not an issue. It's really not that hard.

That includes your New Horizons thing. If you want to contact us, just email us.

**Comment by AutogolazzoJr** [comment]
Where is the fork?

**Comment by DarinMao** [comment]
It's a fork, so it belongs to him. Find it at https://github.comm/mineo333/TSA_Website.

**Comment by AutogolazzoJr** [comment]
Thanks.
