### ISSUE TITLE
Banner for website

### ISSUE THREAD

**Issue by DarinMao** [lighthouse64/TSA_Website#4]
I'd like to have a banner on the top of each page. Now my question is, what is the best way to put that on every page? Obviously we can just copy and paste it into each page, but that's messy and will make adding new pages and editing the banner difficult.
Also, what should we put on the banner? Maybe a little picture in the corner, a title, some links...

Discuss.

**Comment by lighthouse64** [comment]
What do you mean by a banner?  A nav bar?

http://www.w3schools.com/css/css_navbar.asp

**Comment by DarinMao** [comment]
Pretty much, but I'd like to add, like I said, an image and/or title. Using the css navbar might make aligning those difficult.

**Comment by DarinMao** [comment]
My main question was how to add it to the top of each page, so try to focus on that first.

**Comment by DarinMao** [comment]
If we can use PHP on our server we can use the include() statement, but I'm not sure we can use PHP yet.

**Comment by DarinMao** [comment]
I've set up a test server, which supports PHP. That way, we can put 
`<?php include("header.php"); ?>`
on the top of each page, and that will include "header.php"

Also, from now on, create .php files instead of .html. The syntax is exactly the same, if you're not using PHP code.
