### ISSUE TITLE
Php isn't going to work

### ISSUE THREAD

**Issue by lighthouse64** [lighthouse64/TSA_Website#8]
Whatever it is, php doesn't seem like its going to work.  I previewed it on http://htmlpreview.github.io/ and I couldn't see the styling.

**Comment by lighthouse64** [comment]
Or not.  Apparently the css link was broken.

**Comment by DarinMao** [comment]
Go to the website in the README to see it. You can continue to update the files as usual, if you want to see the site with the PHP, ask me to update the server and I will.

**Comment by lighthouse64** [comment]
What's the server?  Also I don't really care if the site is php or not tbh.

**Comment by DarinMao** [comment]
https://mission-to-mars.000webhostapp.com/

PHP is going to let us include the single header and footer files in each page, so if we need to edit the header or footer, we can just edit the one file.

**Comment by DarinMao** [comment]
I'll get a better domain name once we're done.
